### ISSUE TITLE
 vpn

### ISSUE THREAD

**Issue by MCjorsh5** [macrat/hpipe#1]
support openvpn please o v2ray port forwading

**Comment by macrat** [comment]
Thank you for your issue.

If you want to do "VPN over hpipe", you can tunnel VPN's TCP connection using hpipe, like "TCP → http" section in readme. I think you can use every L2 VPN, at least technically.

If you want to do "hpipe over VPN", hpipe works without any settings, because it uses a normal HTTP as transport.

I hope this information helps you.
Please feel free to reopen this issue and tell me how you want to connect them, if you wanted to use this tool in another use case.
